# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q6G6tEfeVnfxgSEBE22dw5pZdtbuQg9p
"""

eta=int(input("Quanti anni hai?"))
biglietto=input("Hai il biglietto?")
if biglietto=="Si":
  print("Puoi entrare")
elif eta>=18:
 print("12€")
elif eta<18:
  print("8€")